[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
gas_reports = ["DiamondGenesisPass", "CentralizedRoyaltyDistributor"]

# Enable Solidity via-IR pipeline for larger functions (helps avoid stack-too-deep)
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
