[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable Solidity via-IR pipeline for larger functions (helps avoid stack-too-deep)
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
